#!/usr/bin/env bash

REPOSITORY_URL='https://github.com/sapagat/katatracker'
OUTPUT_FILE='/tmp/katatracker.txt'
GREEN_COLOR="\033[0;32m"
RED_COLOR="\033[0;31m"
NO_COLOR="\033[0;m"
GREEN_ICON=✅
RED_ICON=❌

test_and_commit() {
  test_command=$@
  fail_if_invalid_test_command $test_command

  test_status="$(run_tests $test_command)"
  print_tests_ouput $test_status
  commit_changes $test_status
}

fail_if_invalid_test_command() {
  test_command=$@
  if [[ -z $test_command ]]; then
    echo "At least a test command is required. For example, rspec or npm test."
    exit 1
  fi
}

run_tests() {
  test_command=$@
  eval $test_command > $OUTPUT_FILE
  if [ $? -eq 0 ]; then
    status='GREEN'
  else
    status='RED'
  fi
  echo $status
}

print_tests_ouput() {
  status=$1
  if [ $status == 'GREEN' ]; then
    color=$GREEN_COLOR
  else
    color=$RED_COLOR
  fi
  printf "${color}$(cat $OUTPUT_FILE)${NO_COLOR}\n"
}

commit_changes() {
  status=$1
  timestamp="$(date +%s)"
  if [ $status == 'GREEN' ]; then
    icon=$GREEN_ICON
  else
    icon=$RED_ICON
  fi
  message_prefix="${icon} ${status} ${timestamp}"

  git add -A
  git commit -m "$message_prefix - CODE"
  if [ $? -eq 0 ]; then
    git commit --allow-empty -m "$message_prefix - OUTPUT" -m "$(cat $OUTPUT_FILE)"
  fi
}

present() {
  ensure_tig_configured
  launch_tig
}

ensure_tig_configured() {
  git config --local --add tig.vertical-split false
  git config --local --add tig.split-view-height 90%
  git config --local --add tig.commit-order reverse
}

launch_tig() {
  tig
}

command=$1
case $command in
  "tc")
    shift
    test_command=$@
    test_and_commit $test_command
    ;;
  "present")
    present
    ;;
  *)
    echo "KataTracker - Increments matter."
    echo
    echo "Supported commands are: tc , present"
    echo
    echo "More details here: ${REPOSITORY_URL}"
esac
