#!/usr/bin/env bash

REPOSITORY_URL='https://github.com/sapagat/katatracker'
OUTPUT_FILE='/tmp/katatracker.txt'
GREEN_ICON=✅
RED_ICON=❌

test_and_commit() {
  test_command=$@
  fail_if_invalid_test_command $test_command

  test_status="$(run_tests $test_command)"
  commit_changes $test_status
}

fail_if_invalid_test_command() {
  test_command=$@
  if [[ -z $test_command ]]; then
    echo "At least a test command is required. For example, rspec or npm test."
    exit 1
  fi
}

run_tests() {
  test_command=$@
  eval $test_command > $OUTPUT_FILE 2>&1
  if [ $? -eq 0 ]; then
    status='GREEN'
  else
    status='RED'
  fi
  echo $status
}

commit_changes() {
  status=$1
  timestamp="$(date +%s)"
  if [ $status == 'GREEN' ]; then
    icon=$GREEN_ICON
  else
    icon=$RED_ICON
  fi
  message_prefix="${icon} ${timestamp}"

  git add -A

  git commit -m "$message_prefix" -m "$(cat $OUTPUT_FILE)"
}

command=$1
case $command in
  "tc")
    shift
    test_command=$@
    test_and_commit $test_command
    ;;
  "watch")
    shift
    test_command=$@
    while inotifywait -qqre modify,create './'; do clear; test_and_commit $test_command; done
    ;;
    *)
    echo "KataTracker - Increments matter."
    echo
    echo "Supported commands are:"
    echo "tc <test-command>"
    echo "watch <test-command>"
    echo
    echo "More details here: ${REPOSITORY_URL}"
esac
